# Site settings
title: Damon Bauer // Front End Developer // Nashville, TN
email: hello@damonbauer.me
description: Damon Bauer - Front End Developer from Nashville, TN. Writing primarily about CSS, Scss and JavaScript. Pretend woodworker. Mountain bike poseur.
baseurl: ""
url: http://damonbauer.me
twitter_username: damon_bauer
github_username:  damonbauer
permalink: /:title/
feed: http://feeds.feedburner.com/damonbauer

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
exclude: ["gulpfile.js", "node_modules", "README.md", "package.json", "Gemfile", "Gemfile.lock", ".editorconfig", ".gitignore"]
